name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, Linux, X64]
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python3 -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/*

      - name: Publish to PyPI
        if: ${{ env.PYPI_TOKEN != '' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
